import { ayebi } from "./types";

export const INSTITUTION_ARTICLES = [
  ayebi("banque-centrale-congo", "Banque Centrale du Congo", "BCC · franc congolais · taux", "institution", "Banque d'émission de la RDC. Politique monétaire, supervision bancaire, statistiques officielles.", ["La BCC publie taux, inflation et réserves.", "Référence pour change et régulation financière."], [{ label: "Sigle", value: "BCC" }, { label: "Site", value: "bcc.cd" }], ["bcc", "banque", "cdf", "taux"]),
  ayebi("unikin", "Université de Kinshasa", "UNIKIN · Lemba", "institution", "Principale université publique, fondée en 1954. Forme juristes, médecins, ingénieurs.", ["Campus de Lemba : facultés diversifiées et recherche.", "Moteur de débat public congolais."], [{ label: "Fondation", value: "1954" }], ["unikin", "université", "kinshasa"]),
  ayebi("unilu", "Université de Lubumbashi", "UNILU · Katanga", "institution", "Grande université du sud-est. Pôle académique minier, juridique et médical.", ["Forme cadres katangais et nationaux.", "Recherche sur mines et environnement."], [{ label: "Ville", value: "Lubumbashi" }], ["unilu", "université", "lubumbashi"]),
  ayebi("snel", "SNEL", "Électricité · réseau national", "institution", "Société nationale d'électricité. Production et distribution d'énergie en RDC.", ["La SNEL gère barrages Inga et réseaux urbains.", "Coupures et réformes structurent le débat public."], [{ label: "Secteur", value: "Énergie" }], ["snel", "électricité", "innga", "énergie"]),
  ayebi("regideso", "REGIDESO", "Eau potable · distribution", "institution", "Régie de distribution d'eau. Service public essentiel dans les grandes villes.", ["REGIDESO approvisionne Kinshasa, Lubumbashi et provinces.", "Investissements visent réduction des pénuries."], [{ label: "Secteur", value: "Eau" }], ["regideso", "eau", "service public"]),
  ayebi("occ", "OCC", "Office congolais de contrôle", "institution", "Contrôle qualité import-export. Certification produits alimentaires et industriels.", ["L'OCC protège consommateurs et commerce.", "Présent aux frontières et ports."], [{ label: "Fonction", value: "Contrôle qualité" }], ["occ", "contrôle", "import"]),
  ayebi("arsp", "ARSP", "Autorité de régulation des postes", "institution", "Régulateur des télécoms et services postaux. Licences opérateurs mobiles.", ["L'ARSP encadre Vodacom, Airtel, Orange.", "Enjeux data, mobile money et couverture rurale."], [{ label: "Secteur", value: "Télécoms" }], ["arsp", "télécom", "mobile"]),
  ayebi("gecamines", "Gécamines", "Mining · État · cuivre cobalt", "institution", "Entreprise publique minière historique du Katanga. Partenaire dans de grands projets cuivre-cobalt.", ["Gécamines détient participations dans plusieurs mines.", "Central à la souveraineté minière congolaise."], [{ label: "Siège", value: "Lubumbashi" }], ["gecamines", "mines", "katanga"]),
  ayebi("inrb", "INRB", "Institut national de recherche biomédicale", "institution", "Centre de recherche santé publique à Kinshasa. Référence épidémiologie et maladies tropicales.", ["L'INRB a joué un rôle clé face à Ebola et COVID.", "Laboratoires et formation médicale avancée."], [{ label: "Ville", value: "Kinshasa" }], ["inrb", "santé", "recherche", "ebola"]),
  ayebi("ceni", "CENI", "Commission électorale nationale", "institution", "Organise élections présidentielles, législatives et locales en RDC.", ["La CENI gère inscriptions, bureaux de vote et résultats.", "Transparence électorale au centre des débats."], [{ label: "Fonction", value: "Élections" }], ["ceni", "élection", "vote", "politique"]),
  ayebi("assemblee-nationale", "Assemblée nationale", "Parlement · législation", "institution", "Chambre basse du Parlement congolais. Vote lois et contrôle gouvernement.", ["Siège au Palais du Peuple.", "500 députés représentent circonscriptions nationales."], [{ label: "Siège", value: "Kinshasa" }], ["assemblée", "parlement", "députés"]),
  ayebi("radio-okapi", "Radio Okapi", "ONU · actualité · RDC", "institution", "Radio d'information de la MONUSCO devenue média national de référence.", ["Couverture provinces, politique et société.", "Site et podcasts très suivis en RDC."], [{ label: "Site", value: "radiookapi.net" }], ["okapi", "radio", "actualité", "news"]),
];

export const ECONOMY_ARTICLES = [
  ayebi("cobalt-rdc", "Cobalt congolais", "Batteries · Katanga · Lualaba", "économie", "La RDC détient la majorité des réserves mondiales de cobalt pour batteries lithium-ion.", ["Production à Kolwezi, Tenke Fungurume et sites artisanaux.", "Enjeux traçabilité et revenus publics."], [{ label: "Régions", value: "Katanga, Lualaba" }], ["cobalt", "mines", "batteries"]),
  ayebi("cuivre-katanga", "Cuivre katangais", "Mining belt · export", "économie", "Le Katanga exporte cuivre raffiné vers la Chine et l'Europe. Pilier macroéconomique national.", ["Joint ventures internationales opèrent vastes mines.", "Prix LME influencent budget congolais."], [{ label: "Hub", value: "Lubumbashi" }], ["cuivre", "katanga", "mines"]),
  ayebi("coltan", "Coltan", "Tantal · électronique · Est", "économie", "Minerai de tantal utilisé en électronique. Exploité en RDC avec enjeux éthiques et sécuritaires.", ["Artisanat minier et industrialisation coexistent.", "Traçabilité demandée par acheteurs internationaux."], [{ label: "Usage", value: "Capacitors · smartphones" }], ["coltan", "tantal", "mines", "est"]),
  ayebi("franc-congolais", "Franc congolais", "CDF · monnaie · BCC", "économie", "Monnaie officielle de la RDC. Taux flottant face au dollar, central à la vie quotidienne.", ["Le CDF structure salaires, marchés et mobile money.", "Dépréciations impactent pouvoir d'achat urbain."], [{ label: "Code", value: "CDF" }], ["franc", "cdf", "monnaie", "taux", "change"]),
  ayebi("code-minier", "Code minier congolais", "Loi · redevances · souveraineté", "économie", "Cadre légal de l'exploitation minière en RDC. Révisions fréquentes sur redevances et contenu local.", ["Le code définit contrats, taxes et obligations sociales.", "Négociations État–miniers font la une économique."], [{ label: "Secteur", value: "Mines" }], ["code minier", "mines", "loi"]),
  ayebi("mobile-money-rdc", "Mobile money", "Vodacom M-Pesa · Airtel · Orange", "économie", "Paiements mobiles essentiels en RDC. Transferts, factures et commerce digital via téléphone.", ["Des millions de transactions quotidiennes.", "Complément au cash dans un contexte bancarisation faible."], [{ label: "Opérateurs", value: "Vodacom, Airtel, Orange" }], ["mobile money", "mpesa", "paiement", "fintech"]),
  ayebi("infrastructure-innga", "Projet Inga", "Barrage · hydroélectricité", "économie", "Grand potentiel hydro sur le fleuve Congo. Inga I, II et projet Inga III pour export et usage national.", ["Inga pourrait alimenter l'Afrique australe.", "Retards et financements complexifient le megaproject."], [{ label: "Fleuve", value: "Congo" }], ["innga", "barrage", "électricité", "snel"]),
  ayebi("agriculture-rdc", "Agriculture congolaise", "Manioc · maïs · potentiel", "économie", "Secteur employant la majorité des Congolais. Manioc, maïs, café et cacao selon régions.", ["Potentiel immense sous-exploité faute de routes et financement.", "Sécurité alimentaire urbaine dépend des provinces."], [{ label: "Emploi", value: "Majoritaire" }], ["agriculture", "manioc", "économie"]),
  ayebi("commerce-transfrontalier", "Commerce transfrontalier", "Zambie · Rwanda · Angola", "économie", "Échanges informels et formels aux frontières. Lubumbashi, Goma et Kasumbalesa sont des hubs.", ["Dollar et francs voisins coexistent dans les marchés.", "Douanes et régulation restent des défis."], [{ label: "Postes", value: "Kasumbalesa, Goma, Matadi" }], ["commerce", "frontière", "zambie", "export"]),
  ayebi("petrole-rdc", "Pétrole congolais", "Cuvette centrale · raffineries", "économie", "Production concentrée en Cuvette centrale. Pipeline vers côte angolaise et raffineries limitées.", ["Le pétrole contribue aux recettes fiscales.", "Potentiel offshore exploré par compagnies internationales."], [{ label: "Région", value: "Cuvette centrale" }], ["pétrole", "oil", "économie"]),
  ayebi("artisanat-minier", "Artisanat minier", "Creuseurs · coopératives · Est-Katanga", "économie", "Des centaines de milliers de creuseurs extraient manuellement minerais. Enjeux sécurité et formalisation.", ["Coopératives et négociants structurent une partie du flux.", "Débats éthiques sur approvisionnement global."], [{ label: "Minerais", value: "Cobalt, coltan, or" }], ["artisanat", "mines", "creuseurs"]),
  ayebi("zone-economique-kinshasa", "Économie de Kinshasa", "Services · import · consommation", "économie", "Kinshasa concentre PIB services, importations et consommation urbaine. Moteur macro national.", ["Gombe, Limete et Marchés structurent l'économie quotidienne.", "Dépendance import alimentaire et pétrolière."], [{ label: "Part PIB", value: "Majoritaire urbaine" }], ["kinshasa", "économie", "pib", "commerce"]),
];
