import { ayebi } from "./types";

export const PLACE_ARTICLES = [
  ayebi("kinshasa", "Kinshasa", "Capitale · mégalopole du Congo", "lieu", "Plus grande ville francophone d'Afrique. Capitale politique et économique de la RDC, face à Brazzaville sur le fleuve Congo.", ["Plus de quinze millions d'habitants dans l'agglomération.", "Gombe, Limete, Matete et la bande fleuve structurent la vie urbaine."], [{ label: "Province", value: "Kinshasa" }, { label: "Fleuve", value: "Congo" }], ["kinshasa", "capitale", "kinois", "ville"]),
  ayebi("lubumbashi", "Lubumbashi", "Capitale du Haut-Katanga · mining hub", "lieu", "Deuxième ville de la RDC. Pôle minier, universitaire et logistique du sud-est, capitale historique du Katanga.", ["Lubumbashi concentre raffineries, universités et le stade TP Mazembe.", "La ville est porte d'entrée commerciale vers la Zambie et l'Afrique australe."], [{ label: "Province", value: "Haut-Katanga" }, { label: "Population", value: "~3 millions" }], ["lubumbashi", "katanga", "ville", "mines"]),
  ayebi("goma", "Goma", "Capitale du Nord-Kivu · bord du lac Kivu", "lieu", "Ville dynamique de l'Est, proche du volcan Nyiragongo. Centre humanitaire, commercial et touristique du Kivu.", ["Goma vit au rythme du lac, des ONG et du commerce transfrontalier.", "Les éruptions volcaniques et l'insécurité structurent son histoire récente."], [{ label: "Province", value: "Nord-Kivu" }, { label: "Volcan", value: "Nyiragongo" }], ["goma", "kivu", "nyiragongo", "est"]),
  ayebi("bukavu", "Bukavu", "Capitale du Sud-Kivu · collines du Kivu", "lieu", "Ville lacustre au relief escarpé. Centre administratif, universitaire et artisanal du Sud-Kivu.", ["Bukavu accueille l'Université catholique et l'hôpital Panzi.", "Son port lacustre relie le Sud-Kivu au reste de la région."], [{ label: "Province", value: "Sud-Kivu" }, { label: "Lac", value: "Kivu" }], ["bukavu", "kivu", "sud-kivu"]),
  ayebi("kisangani", "Kisangani", "Capitale de la Tshopo · confluence", "lieu", "Grande ville fluviale au confluent du Congo et de la Tshopo. Ancienne Stanleyville, carrefour de l'Est intérieur.", ["Kisangani est un hub logistique fluvial vers Kinshasa et l'Est.", "Universités, marchés et forêt bordent la métropole tropicale."], [{ label: "Province", value: "Tshopo" }, { label: "Fleuve", value: "Congo" }], ["kisangani", "tshopo", "fleuve", "ville"]),
  ayebi("matadi", "Matadi", "Port principal · Kongo Central", "lieu", "Ville-port sur le fleuve Congo et point de sortie maritime via l'Angola. Porte économique du pays vers l'Atlantique.", ["Matadi concentre entrepôts, douanes et trafic de conteneurs.", "Le pont Matadi-Kinshasa relie le port à la capitale."], [{ label: "Province", value: "Kongo Central" }, { label: "Fonction", value: "Port en eau profonde" }], ["matadi", "port", "kongo central", "commerce"]),
  ayebi("mbuji-mayi", "Mbuji-Mayi", "Capitale du Kasaï · diamants", "lieu", "Capitale du Kasaï-Oriental et centre historique de l'exploitation diamantifère artisanale et industrielle.", ["Mbuji-Mayi vit au rythme du diamant et du commerce kasaïen.", "La ville est un carrefour lingala et tshiluba."], [{ label: "Province", value: "Kasaï-Oriental" }, { label: "Ressource", value: "Diamants" }], ["mbuji-mayi", "kasai", "diamant"]),
  ayebi("kananga", "Kananga", "Capitale du Kasaï-Central", "lieu", "Ville du Grand Kasaï, centre administratif et culturel tshiluba.", ["Kananga accueille universités et marchés agricoles.", "Elle joue un rôle politique majeur dans le centre du pays."], [{ label: "Province", value: "Kasaï-Central" }], ["kananga", "kasai", "ville"]),
  ayebi("stade-des-martyrs", "Stade des Martyrs", "Kinshasa · 80 000 places", "lieu", "Principal stade de Kinshasa. Temple du football congolais, concerts et grands rassemblements nationaux.", ["Inauguré en 1994 à Lingwala.", "Accueille Léopards, finales nationales et stars congolaises."], [{ label: "Capacité", value: "~80 000" }, { label: "Quartier", value: "Lingwala" }], ["stade", "martyrs", "football", "kinshasa"]),
  ayebi("stade-tp-mazembe", "Stade TP Mazembe", "Lubumbashi · Mazembe", "lieu", "Enceinte du Tout-Puissant Mazembe, club le plus titré d'Afrique. Chaudron du football katangais.", ["Le stade vibre lors des matchs CAF et des derbys locaux.", "Katumbi et les supporters ont modernisé l'infrastructure."], [{ label: "Club", value: "TP Mazembe" }, { label: "Ville", value: "Lubumbashi" }], ["mazembe", "stade", "lubumbashi", "football"]),
  ayebi("marche-central-kinshasa", "Marché Central", "Kinshasa · alimentation · textile", "lieu", "Grand marché kinshois. Baromètre des prix alimentaires et hub de distribution urbaine.", ["Grossistes et détaillants y négocient manioc, poisson, huile et wax.", "Les variations du dollar se lisent immédiatement sur les étals."], [{ label: "Ville", value: "Kinshasa" }], ["marché", "central", "kinshasa", "prix", "commerce"]),
  ayebi("marche-liberte-lubumbashi", "Marché Liberté", "Lubumbashi · commerce katangais", "lieu", "L'un des plus grands marchés de Lubumbashi. Centre de distribution pour le Katanga et la Zambie voisine.", ["On y trouve produits miniers artisanaux, alimentation et importations zambiennes.", "Le marché reflète l'économie transfrontalière du copperbelt."], [{ label: "Ville", value: "Lubumbashi" }], ["marché", "liberté", "lubumbashi", "katanga"]),
  ayebi("parc-national-virunga", "Parc national des Virunga", "UNESCO · gorilles · Nyiragongo", "lieu", "Plus ancien parc national d'Afrique. Abrite gorilles de montagne, Nyiragongo et biodiversité exceptionnelle.", ["Le parc emploie des gardes et soutient le tourisme scientifique.", "Conflits armés et braconnage menacent durablement le site."], [{ label: "Création", value: "1925" }, { label: "UNESCO", value: "Oui" }], ["virunga", "gorille", "nyiragongo", "parc", "goma"]),
  ayebi("fleuve-congo", "Fleuve Congo", "Deuxième fleuve d'Afrique · axe national", "lieu", "Artère fluviale majeure traversant la RDC. Voie de transport, pêche et identité nationale.", ["Le fleuve relie Kisangani, Mbandaka et Kinshasa.", "Barges et pirogues restent essentielles à l'économie intérieure."], [{ label: "Longueur", value: "~4 700 km" }], ["fleuve", "congo", "transport", "barge"]),
  ayebi("lac-kivu", "Lac Kivu", "Frontière RDC–Rwanda · gaz dissous", "lieu", "Lac des Grands Lacs africains bordant Goma et Bukavu. Ressource en poisson et en gaz naturel dissous.", ["Le lac est au cœur de l'économie kivuise.", "Des projets exploitent le méthane lacustre pour l'électricité."], [{ label: "Villes", value: "Goma, Bukavu" }], ["lac", "kivu", "goma", "bukavu"]),
  ayebi("mont-nyiragongo", "Mont Nyiragongo", "Volcan actif · Goma", "lieu", "Volcan du rift est-africain avec l'un des lacs de lave les plus actifs au monde. Menace directe sur Goma.", ["Éruptions majeures en 2002 et 2021 ont déplacé des centaines de milliers de personnes.", "L'OVG surveille en permanence l'activité sismique."], [{ label: "Hauteur", value: "3 470 m" }, { label: "Ville proche", value: "Goma" }], ["nyiragongo", "volcan", "goma", "éruption"]),
  ayebi("aeroport-ndjili", "Aéroport de N'djili", "Kinshasa · hub aérien national", "lieu", "Principal aéroport international de la RDC. Porte d'entrée aérienne de Kinshasa et hub Congo Airways.", ["N'djili accueille vols régionaux et intercontinentaux.", "Travaux et modernisation visent à absorber la croissance du trafic."], [{ label: "Code", value: "FIH" }, { label: "Ville", value: "Kinshasa" }], ["ndjili", "aéroport", "kinshasa", "aviation"]),
  ayebi("palais-de-la-nation", "Palais de la Nation", "Kinshasa · présidence", "lieu", "Siège de la présidence de la République à Kinshasa. Lieu protocolaire des investitures et sommets officiels.", ["Le palais domine la colline de la Gombe.", "Il symbolise le pouvoir exécutif central."], [{ label: "Quartier", value: "Gombe" }], ["palais", "nation", "présidence", "kinshasa"]),
  ayebi("palais-du-peuple", "Palais du Peuple", "Kinshasa · Parlement", "lieu", "Siège de l'Assemblée nationale et du Sénat. Plus grand bâtiment d'Afrique subsaharienne par sa superficie.", ["Construit à l'époque Mobutu, il accueille sessions parlementaires et grands événements.", "Symbole institutionnel de la IIIe République."], [{ label: "Fonction", value: "Parlement" }], ["palais", "peuple", "parlement", "assemblée"]),
  ayebi("pont-wagenia", "Chutes Wagenia", "Kisangani · cataractes du Congo", "lieu", "Célèbres rapides du fleuve Congo près de Kisangani. Pêche traditionnelle au basket et site touristique.", ["Les pêcheurs Wagenia installent des nasses en bambou dans les cataractes.", "Les chutes alimentent l'imaginaire national et le tourisme local."], [{ label: "Ville", value: "Kisangani" }], ["wagenia", "chutes", "kisangani", "fleuve"]),
];
