import { ayebi } from "./types";

export const CULTURE_ARTICLES = [
  ayebi("rumba-congolaise", "Rumba congolaise", "UNESCO · guitare · danse", "culture", "Genre musical emblématique RDC–Congo, inscrit au patrimoine UNESCO. Fusion jazz, latin et traditions locales.", ["Née à Léopoldville et Brazzaville dans les années 40-50.", "Franco, Tabu Ley et Papa Wemba l'exportent sur tout le continent."], [{ label: "UNESCO", value: "2021" }], ["rumba", "musique", "culture"]),
  ayebi("franco-luambo", "Franco Luambo", "Grand maître · OK Jazz", "culture", "Guitariste et chanteur légendaire, chef de l'OK Jazz (TPOK Jazz). Figure tutélaire de la rumba.", ["Franco enregistre des centaines de chansons commentant la société zaïroise.", "Son héritage structure encore la musique congolaise."], [{ label: "Orchestre", value: "TPOK Jazz" }], ["franco", "ok jazz", "rumba", "musique"]),
  ayebi("tabu-ley", "Tabu Ley Rochereau", "Chanteur · Afrisa · politique", "culture", "Star de la rumba, fondateur d'Afrisa. Député et ministre, il marie musique et engagement public.", ["Tabu Ley modernise la scène avec des arrangements sophistiqués.", "Ses titres restent des classiques des mariages congolais."], [{ label: "Orchestre", value: "Afrisa" }], ["tabu ley", "afrisa", "rumba"]),
  ayebi("papa-wemba", "Papa Wemba", "Sapeur · Viva la Musica", "culture", "Icône de la rumba et pape de la Sape (Société des ambianceurs). Influence mode et musique mondiale.", ["Papa Wemba popularise la sape parisienne et kinshasaise.", "Son décès en 2016 provoque un deuil national."], [{ label: "Mouvement", value: "Sape" }], ["papa wemba", "sape", "rumba"]),
  ayebi("koffi-olomide", "Koffi Olomide", "Ndombolo · Quartier Latin", "culture", "Chanteur et producteur, pionnier du ndombolo dans les années 90. Leader du Quartier Latin International.", ["Koffi domine les charts congolais et africains depuis trois décennies.", "Ses concerts remplissent stades en RDC et en diaspora."], [{ label: "Genre", value: "Ndombolo" }], ["koffi", "ndombolo", "quartier latin"]),
  ayebi("fally-ipupa", "Fally Ipupa", "Pop congolaise · international", "culture", "Chanteur star de la nouvelle génération. Ex-D'banj, ex-Quartier Latin, carrière solo mondiale.", ["Fally fusionne rumba, R&B et afrobeats.", "Il est ambassadeur culturel de la RDC à l'international."], [{ label: "Genre", value: "Rumba moderne" }], ["fally", "ipupa", "musique"]),
  ayebi("werrason", "Werrason", "King of African Dance · Maison Mère", "culture", "Leader de Wenge Maison Mère, figure du ndombolo et rival historique de JB Mpiana.", ["Werrason structure un empire musical et des danseurs emblématiques.", "Son influence dépasse la scène strictly musicale."], [{ label: "Groupe", value: "Maison Mère" }], ["werrason", "ndombolo", "wenge"]),
  ayebi("ndombolo", "Ndombolo", "Danse · rythme · années 90", "culture", "Genre musical et danse née à Kinshasa, popularisée par Wenge et Koffi Olomide. Rythme syncopé et danse du ventre.", ["Le ndombolo transforme clubs, radios et mode vestimentaire.", "Il reste dominant dans les fêtes congolaises."], [{ label: "Origine", value: "Kinshasa · années 90" }], ["ndombolo", "danse", "musique"]),
  ayebi("zaiko-langa-langa", "Zaiko Langa Langa", "Orchestre · evolution rumba", "culture", "Groupe fondateur né en 1969, père de nombreux musiciens congolais. Laboratoire du son modern congolais.", ["Zaiko introduit sebene, mi-solo et esthétique jeunesse.", "Ses splits créent Wenge et autres dynasties."], [{ label: "Fondation", value: "1969" }], ["zaiko", "rumba", "musique"]),
  ayebi("lingala-langue", "Lingala", "Langue nationale · musique · armée", "culture", "Langue véhiculaire de la RDC, parlée à Kinshasa et le long du fleuve. Langue des lyrics congolais.", ["Le lingala unit zones urbaines au-delà des langues ethniques.", "Dictionnaires et radios popularisent le vocabulaire quotidien."], [{ label: "Parleurs", value: "Dizaines de millions" }], ["lingala", "langue", "dictionnaire"]),
  ayebi("sape-congolaise", "Sape congolaise", "Société des ambianceurs · mode", "culture", "Mouvement esthétique célébrant l'habillement chic. Né à Brazzaville et Kinshasa, exporté en diaspora.", ["La sape mêle créativité, marques européennes et performance sociale.", "Papa Wemba en est le parrain le plus connu."], [{ label: "Sigle", value: "SAPE" }], ["sape", "mode", "kinshasa", "culture"]),
  ayebi("cinema-congolais", "Cinéma congolais", "Nollywood kin · séries · festivals", "culture", "Industrie audiovisuelle en croissance : séries YouTube, cinéma populaire et festivals à Kinshasa.", ["Des créateurs produisent des séries en lingala pour des millions de vues.", "Le cinéma congolais raconte la vie urbaine sans filtres."], [{ label: "Hub", value: "Kinshasa" }], ["cinéma", "film", "série", "culture"]),
];

export const SPORT_ARTICLES = [
  ayebi("leopards-rdc", "Équipe nationale (Léopards)", "CAN 1968 · 1974 · FIFA", "sport", "Sélection congolaise de football. Championne d'Afrique sous le nom Zaïre.", ["Les Léopards restent un vecteur d'unité nationale.", "Stade des Martyrs concentre l'effervescence des supporteurs."], [{ label: "Titres CAN", value: "1968, 1974" }, { label: "Fédération", value: "FECOFA" }], ["leopards", "football", "fecofa", "can"]),
  ayebi("tp-mazembe", "TP Mazembe", "Club · Lubumbashi · CAF", "sport", "Club le plus titré d'Afrique. Vainqueur Ligue des champions CAF, finaliste Coupe du monde des clubs.", ["Le Mazembe est une institution katangaise et nationale.", "Katumbi a modernisé infrastructure et recrutement."], [{ label: "Ville", value: "Lubumbashi" }, { label: "Titres CAF", value: "Multiple" }], ["mazembe", "football", "lubumbashi", "caf"]),
  ayebi("as-vita-club", "AS Vita Club", "Club · Kinshasa · Congo", "sport", "Club historique de Kinshasa, multiple champion national. Rival de DCMP et Mukondo.", ["Vita Club forme des générations de joueurs congolais.", "Le stade des Martyrs est son théâtre principal."], [{ label: "Ville", value: "Kinshasa" }], ["vita", "football", "kinshasa"]),
  ayebi("daring-club-mpongo", "DCMP", "Daring Club · Kinshasa", "sport", "Club emblématique de Kinshasa, aux couleurs vert et blanc. Base de formation et rivalités historiques.", ["DCMP possède une base de supporters passionnée.", "Derbys contre Vita et Motema Pembe rythment la ligue."], [{ label: "Surnom", value: "Daring" }], ["dcmp", "football", "kinshasa"]),
  ayebi("cedric-bakambu", "Cédric Bakambu", "Attaquant · Léopards · Europe", "sport", "International congolais, buteur en Liga et Superlig. Figure de l'export footballistique congolais.", ["Bakambu incarne la diaspora sportive performante.", "Il porte le maillot des Léopards en compétitions africaines."], [{ label: "Poste", value: "Attaquant" }], ["bakambu", "football", "leopards"]),
  ayebi("dieumerci-mbokani", "Dieumerci Mbokani", "Attaquant · légende Léopards", "sport", "Avant-centre expérimenté, buteur historique des Léopards et des clubs européens.", ["Mbokani est une référence générationnelle.", "Sa carrière inspire les jeunes attaquants congolais."], [{ label: "Poste", value: "Attaquant" }], ["mbokani", "football", "leopards"]),
  ayebi("fecofa", "FECOFA", "Fédération congolaise de football", "sport", "Instance régissant le football en RDC : championnat Linafoot, coupes et sélections nationales.", ["La FECOFA organise compétitions et développement des académies.", "Elle représente la RDC auprès de la CAF et FIFA."], [{ label: "Siège", value: "Kinshasa" }], ["fecofa", "football", "linafoot"]),
  ayebi("linafoot", "Linafoot", "Championnat national · D1", "sport", "Championnat professionnel de football congolais. Saison longue avec clubs de toutes les provinces.", ["Vita, Mazembe et DCMP dominent historiquement.", "La ligue pro progresse en structuration et droits TV."], [{ label: "Niveau", value: "Division 1" }], ["linafoot", "championnat", "football"]),
  ayebi("basketball-congo", "Basketball congolais", "NBA · diaspora · championnat", "sport", "Sport en croissance avec Mutombo comme icône. Championnat national et joueurs en NCAA/NBA.", ["Kinshasa et Lubumbashi accueillent des équipes compétitives.", "La diaspora alimente les sélections jeunes."], [{ label: "Icône", value: "Dikembe Mutombo" }], ["basketball", "mutombo", "sport"]),
  ayebi("boxe-congolaise", "Boxe congolaise", "Ring · champions · Kinshasa", "sport", "Tradition boxe à Kinshasa et Lubumbashi. Formation de champions africains et olympiques.", ["Clubs historiques forment des boxeurs exportés.", "La boxe reste populaire dans les quartiers."], [{ label: "Villes", value: "Kinshasa, Lubumbashi" }], ["boxe", "sport", "kinshasa"]),
];
