import type { AyebiArticle } from "./types";

/** Titres Wikipedia FR — overrides quand le titre Ayebi ne correspond pas */
export const WIKI_TITLE_OVERRIDES: Record<string, string> = {
  "aeroport-ndjili": "Aéroport_international_de_N'djili",
  "agriculture-rdc": "Agriculture_en_République_démocratique_du_Congo",
  "artisanat-minier": "Mine_artisanale",
  "assemblee-nationale": "Assemblée_nationale_(République_démocratique_du_Congo)",
  "as-vita-club": "Association_Sportive_Vita_Club",
  "banque-centrale-congo": "Banque_centrale_du_Congo",
  "basketball-congo": "Équipe_de_République_démocratique_du_Congo_de_basket-ball",
  "boxe-congolaise": "Boxe_en_République_démocratique_du_Congo",
  "ceni": "Commission_électorale_nationale_indépendante",
  "cinema-congolais": "Cinéma_en_République_démocratique_du_Congo",
  "cobalt-rdc": "Cobalt",
  "code-minier": "Code_minier_(République_démocratique_du_Congo)",
  "coltan": "Coltan",
  "commerce-transfrontalier": "Commerce_en_République_démocratique_du_Congo",
  "cuivre-katanga": "Cuivre",
  "daring-club-mpongo": "Daring_Club_Motema_Pembe",
  "denis-mukwege": "Denis_Mukwege",
  "dikembe-mutombo": "Dikembe_Mutombo",
  "etienne-tshisekedi": "Étienne_Tshisekedi",
  "fecofa": "Fédération_congolaise_de_football",
  "felix-tshisekedi": "Félix_Tshisekedi",
  "fally-ipupa": "Fally_Ipupa",
  "franc-congolais": "Franc_congolais",
  "franco-luambo": "Franco_Luambo",
  "fleuve-congo": "Congo_(fleuve)",
  "infrastructure-innga": "Barrage_d'Inga",
  "jean-pierre-bemba": "Jean-Pierre_Bemba",
  "joseph-kabila": "Joseph_Kabila",
  "kasa-vubu": "Joseph_Kasa-Vubu",
  "koffi-olomide": "Koffi_Olomide",
  "laurent-desire-kabila": "Laurent-Désiré_Kabila",
  "leopards-rdc": "Équipe_de_République_démocratique_du_Congo_de_football",
  "lingala-langue": "Lingala",
  "linafoot": "Championnat_de_République_démocratique_du_Congo_de_football",
  "lac-kivu": "Lac_Kivu",
  "martin-fayulu": "Martin_Fayulu",
  "mobile-money-rdc": "Paiement_mobile",
  "mobutu-sese-seko": "Mobutu_Sese_Seko",
  "moise-katumbi": "Moïse_Katumbi",
  "mont-nyiragongo": "Nyiragongo",
  "ndombolo": "Ndombolo",
  "palais-de-la-nation": "Palais_de_la_Nation_(Kinshasa)",
  "palais-du-peuple": "Palais_du_peuple",
  "papa-wemba": "Papa_Wemba",
  "parc-national-virunga": "Parc_national_des_Virunga",
  "petrole-rdc": "Pétrole_en_République_démocratique_du_Congo",
  "pont-wagenia": "Chutes_Wagenia",
  "radio-okapi": "Radio_Okapi",
  "rumba-congolaise": "Rumba_congolaise",
  "sape-congolaise": "SAPE",
  "stade-des-martyrs": "Stade_des_Martyrs",
  "stade-tp-mazembe": "Stade_TP_Mazembe",
  "tabu-ley": "Tabu_Ley",
  "tp-mazembe": "Tout_Puissant_Mazembe",
  "vital-kamerhe": "Vital_Kamerhe",
  "werrason": "Werrason",
  "zaiko-langa-langa": "Zaïko_Langa_Langa",
  "zone-economique-kinshasa": "Kinshasa",
};

export function wikiTitleForArticle(article: AyebiArticle): string {
  return WIKI_TITLE_OVERRIDES[article.slug] ?? article.title.replace(/ /g, "_");
}
