/**
 * Expansion de requêtes — synonymes, abréviations et pont FR↔EN minimal.
 *
 * Objectif : « monnaie rdc » doit retrouver « franc congolais » même si le doc
 * ne contient jamais le token « rdc » ; « java langage » doit retrouver la doc
 * Oracle en anglais. Chaque token est élargi en GROUPE OR — la précision de la
 * requête AND est préservée (un doc doit matcher au moins une variante par
 * groupe), le rappel augmente.
 *
 * La map est volontairement prudente : pas d'expansion pour les termes
 * ambigus (« congo » seul peut désigner Brazzaville — on n'étend QUE « rdc »).
 */

/** Mots-outils français — exclus du MATCH AND et du calcul de couverture. */
export const FR_STOPWORDS = new Set([
  "le", "la", "les", "de", "du", "des", "un", "une", "et", "ou", "au", "aux",
  "en", "dans", "sur", "par", "pour", "avec", "sans", "sous", "entre", "chez",
  "est", "sont", "ete", "être", "etre", "a", "à", "ont", "fait", "faire",
  "quel", "quelle", "quels", "quelles", "qui", "que", "quoi", "comment",
  "pourquoi", "quand", "où", "ce", "cet", "cette", "ces", "son", "sa", "ses",
  "mon", "ma", "mes", "ton", "ta", "tes", "notre", "votre", "leur", "leurs",
  "je", "tu", "il", "elle", "on", "nous", "vous", "ils", "elles", "se", "si",
  "ne", "pas", "plus", "moins", "tres", "très", "bien", "comme", "mais",
  "donc", "car", "y", "tout", "tous", "toute", "toutes", "meme", "même",
  "aussi", "autre", "autres", "dire", "dit", "trouve", "trouver", "situe",
  "situé", "situee", "située", "veut", "veux", "voir", "savoir", "connaitre",
  "connaître", "donner", "donne", "moi", "me", "toi", "te", "lui", "eux",
  "elle", "cela", "celui", "celle", "ceci", "ici", "la", "là", "oui", "non",
  "peu", "beaucoup", "encore", "deja", "déjà", "puis", "alors", "ainsi",
  "quelque", "quelques", "chaque", "tres", "plupart", "partie", "nom",
  "liste", "exemple", "info", "infos", "information", "informations",
  "site", "page", "article", "quelqu", "kimaya", // « kimaya » argot — neutre
]);

/**
 * Variantes par token (normalisé minuscule sans accent).
 * FR↔EN limité aux termes fréquents où le web pertinent est souvent anglais.
 */
const EXPANSIONS: Record<string, string[]> = {
  // Abréviations / noms propres régionaux
  rdc: ["congo", "congolais", "congolaise", "zaire"],
  congolais: ["rdc", "congo"],
  congolaise: ["rdc", "congo"],
  zaire: ["rdc", "congo", "congolais"],
  udps: ["tshisekedi", "parti"],
  bcdc: ["banque", "commerciale", "congo"],
  bcc: ["banque", "centrale", "congo"],
  monusco: ["onu", "nations"],
  onu: ["nations", "unies", "united"],
  usa: ["etats", "unis", "amerique", "american", "united"],
  "etats-unis": ["usa", "amerique", "american"],
  ue: ["europe", "europeenne", "european"],
  tv: ["television", "télévision"],
  télé: ["television", "tv"],
  // Fonctions / institutions (sémantique RDC : ville → gouverneur pas maire)
  maire: ["gouverneur", "ville"],
  gouverneur: ["maire", "province"],
  ministre: ["ministere", "ministère"],
  senateur: ["senat", "sénateur"],
  depute: ["député", "assemblee", "assemblée", "parlement"],
  // Quotidien FR
  hopital: ["hôpital", "clinique", "hospital"],
  hôpital: ["hopital", "clinique"],
  medecin: ["médecin", "docteur"],
  médecin: ["medecin", "docteur"],
  docteur: ["medecin", "médecin"],
  ecole: ["école", "universite", "université", "school"],
  école: ["ecole", "universite", "school"],
  universite: ["université", "university", "ecole"],
  université: ["universite", "university"],
  lycee: ["lycée", "ecole", "school"],
  lycée: ["lycee", "ecole"],
  emploi: ["job", "travail", "recrutement", "offre"],
  job: ["emploi", "travail"],
  travail: ["emploi", "job"],
  stage: ["emploi", "internship"],
  salaire: ["remuneration", "rémunération", "paye", "salaire"],
  prix: ["cout", "coût", "tarif", "cost", "price"],
  cout: ["prix", "tarif", "cost"],
  coût: ["prix", "tarif", "cost"],
  tarif: ["prix", "cout", "price"],
  gratuit: ["free", "gratuite"],
  photo: ["image", "photos", "picture"],
  image: ["photo", "picture"],
  video: ["vidéo", "video", "film"],
  vidéo: ["video", "film"],
  musique: ["music", "chanson", "song"],
  chanson: ["musique", "song"],
  chanteur: ["singer", "artiste"],
  chanteuse: ["singer", "artiste"],
  acteur: ["actor", "actrice"],
  actrice: ["actress", "acteur"],
  film: ["movie", "cinema", "cinéma"],
  serie: ["série", "series", "tv"],
  série: ["serie", "series"],
  livre: ["book", "roman"],
  roman: ["livre", "novel", "book"],
  auteur: ["author", "ecrivain", "écrivain"],
  ecrivain: ["écrivain", "auteur", "author"],
  écrivain: ["ecrivain", "auteur", "author"],
  recette: ["cuisine", "recipe", "plat"],
  restaurant: ["resto", "manger", "restaurant"],
  hotel: ["hôtel", "hotel", "hebergement", "hébergement"],
  hôtel: ["hotel", "hebergement"],
  aeroport: ["aéroport", "airport", "vol"],
  aéroport: ["aeroport", "airport"],
  vol: ["aeroport", "flight", "avion"],
  avion: ["vol", "flight", "aeroport"],
  billet: ["ticket", "vol", "avion"],
  // Termes encyclopédiques / factuels
  capitale: ["capital"],
  capital: ["capitale"],
  president: ["président", "president", "dirigeant"],
  président: ["president", "dirigeant"],
  dirigeant: ["president", "président", "leader"],
  gouvernement: ["government", "etat", "état"],
  premier: ["premier", "primature"],
  population: ["habitants", "peuple", "people"],
  habitants: ["population"],
  monnaie: ["devise", "currency", "money", "argent"],
  devise: ["monnaie", "currency"],
  langue: ["language", "langage"],
  histoire: ["history", "historique"],
  guerre: ["war", "conflit", "conflit"],
  conflit: ["guerre", "war"],
  economie: ["économie", "economy"],
  économie: ["economie", "economy"],
  naissance: ["ne", "né", "nee", "née", "birth", "born"],
  ne: ["né", "naissance", "born"],
  né: ["ne", "naissance", "born"],
  nee: ["née", "naissance", "born"],
  née: ["nee", "naissance", "born"],
  mort: ["deces", "décès", "death", "died"],
  deces: ["décès", "mort", "death"],
  décès: ["deces", "mort", "death"],
  age: ["âge", "ans", "old"],
  âge: ["age", "ans"],
  taille: ["height", "grandeur"],
  poids: ["weight"],
  femme: ["wife", "epouse", "épouse", "woman"],
  epouse: ["épouse", "femme", "wife"],
  épouse: ["epouse", "femme", "wife"],
  mari: ["husband", "epoux", "époux", "conjoint"],
  epoux: ["époux", "mari", "husband"],
  époux: ["epoux", "mari", "husband"],
  conjoint: ["mari", "epouse", "wife", "husband"],
  conjointe: ["femme", "epouse", "wife", "husband"],
  fils: ["son", "enfant"],
  fille: ["daughter", "enfant"],
  frere: ["frère", "brother"],
  frère: ["frere", "brother"],
  soeur: ["sœur", "sister"],
  sœur: ["soeur", "sister"],
  ville: ["city", "cite", "cité"],
  pays: ["country", "etat", "nation"],
  village: ["cite", "ville"],
  province: ["region", "région"],
  region: ["région", "province"],
  région: ["region", "province"],
  ile: ["île", "island"],
  île: ["ile", "island"],
  fleuve: ["river", "riviere"],
  riviere: ["rivière", "fleuve", "river"],
  rivière: ["riviere", "fleuve"],
  lac: ["lake"],
  volcan: ["volcano"],
  montagne: ["mountain", "mont"],
  stade: ["stadium"],
  equipe: ["équipe", "team", "club"],
  équipe: ["equipe", "team"],
  joueur: ["player"],
  joueuse: ["player"],
  club: ["equipe", "équipe", "team"],
  championnat: ["championship", "league", "ligue"],
  ligue: ["league", "championnat"],
  match: ["game"],
  but: ["goal"],
  football: ["soccer", "foot", "foot"],
  foot: ["football", "soccer"],
  // Actions / intentions
  telecharger: ["télécharger", "download"],
  télécharger: ["telecharger", "download"],
  acheter: ["acheter", "buy", "achat", "vente", "shop"],
  achat: ["acheter", "buy", "vente", "shop"],
  vente: ["vendre", "acheter", "sale", "shop"],
  vendre: ["vente", "sell", "acheter"],
  louer: ["location", "rent", "louer"],
  location: ["louer", "rent"],
  immobilier: ["maison", "appartement", "location", "real", "estate"],
  maison: ["house", "immobilier", "home"],
  appartement: ["apartment", "immobilier", "location"],
  voiture: ["car", "vehicule", "véhicule", "auto"],
  vehicule: ["véhicule", "voiture", "car"],
  véhicule: ["vehicule", "voiture", "car"],
  // Tech / dev
  langage: ["language", "programmation", "programming"],
  programmation: ["programming", "code", "langage"],
  code: ["programmation", "programming", "source"],
  tutoriel: ["tutorial", "guide", "cours"],
  cours: ["tutorial", "tutoriel", "formation", "course"],
  formation: ["cours", "training", "tutorial"],
  logiciel: ["software", "app", "application"],
  application: ["app", "logiciel", "software"],
  app: ["application", "logiciel"],
  ordinateur: ["computer", "pc"],
  telephone: ["téléphone", "phone", "numero", "numéro", "contact"],
  téléphone: ["telephone", "phone", "numero", "contact"],
  numero: ["numéro", "telephone", "téléphone", "phone"],
  numéro: ["numero", "telephone", "phone"],
  contact: ["telephone", "téléphone", "numero", "phone", "email"],
  email: ["mail", "e-mail", "courriel", "contact"],
  mail: ["email", "e-mail", "courriel"],
  motdepasse: ["mot", "passe", "password"],
  password: ["mot", "passe", "password"],
  // Divers intentionnels
  actualite: ["actualité", "news", "info", "infos", "nouvelle", "nouvelles"],
  actualité: ["actualite", "news", "info", "nouvelle"],
  nouvelle: ["actualite", "actualité", "news"],
  nouvelles: ["actualite", "news"],
  info: ["actualite", "actualité", "news", "information"],
  infos: ["actualite", "news", "informations"],
  journal: ["news", "actualite", "presse", "newspaper"],
  presse: ["journal", "media", "news"],
  media: ["média", "presse", "news"],
  média: ["media", "presse"],
  meteo: ["météo", "weather", "climat", "temps"],
  météo: ["meteo", "weather", "climat"],
  climat: ["meteo", "climate", "weather"],
  horaire: ["heure", "ouverture", "schedule", "hours"],
  ouverture: ["horaire", "ouvert", "hours", "open"],
  ferme: ["fermé", "closed", "ouverture"],
  fermé: ["ferme", "closed"],
  adresse: ["address", "situe", "situé", "localisation"],
  localisation: ["adresse", "ou", "où", "location", "map"],
  carte: ["map", "localisation", "plan"],
  plan: ["carte", "map"],
  distance: ["loin", "proche", "km"],
  proche: ["distance", "pres", "près", "near"],
  pres: ["près", "proche", "near"],
  près: ["pres", "proche", "near"],
  loin: ["distance", "far"],
  heure: ["horaire", "time", "schedule"],
  agenda: ["calendrier", "programme", "schedule"],
  calendrier: ["agenda", "calendar", "programme"],
  programme: ["agenda", "calendrier", "schedule"],
  resultat: ["résultat", "result", "score"],
  résultat: ["resultat", "result", "score"],
  classement: ["ranking", "classement", "tableau"],
  definition: ["définition", "definition", "signification", "meaning"],
  définition: ["definition", "signification", "meaning"],
  signification: ["definition", "définition", "meaning"],
  synonyme: ["synonym", "pareil", "similaire"],
  traduction: ["translation", "traduire", "translate"],
  traduire: ["traduction", "translate"],
};

/** Variantes d'un token (sans le token lui-même). */
export function expandToken(token: string): string[] {
  return EXPANSIONS[token.toLowerCase()] ?? [];
}
