/** Graines massives — file extensible vers milliards via découverte de liens + sitemaps */
export const MEGA_SEEDS = [
  // === RDC gouvernement & institutions ===
  "https://www.presidence.cd/",
  "https://www.primature.cd/",
  "https://www.assemblee-nationale.cd/",
  "https://www.senat.cd/",
  "https://www.ceni.cd/",
  "https://www.bcc.cd/",
  "https://www.arsp.cd/",
  "https://www.anrmp.cd/",
  "https://www.anapi.cd/",
  "https://mines.gouv.cd/",
  "https://www.education.gouv.cd/",
  "https://www.sante.gouv.cd/",
  "https://www.finances.gouv.cd/",
  "https://www.defense.gouv.cd/",
  "https://www.justice.gouv.cd/",
  "https://www.transport.gouv.cd/",
  "https://www.agriculture.gouv.cd/",
  "https://www.environnement.gouv.cd/",
  "https://www.culture.gouv.cd/",
  "https://www.sports.gouv.cd/",
  "https://www.snel.cd/",
  "https://www.regideso.cd/",
  "https://www.ocpt.cd/",
  "https://www.inrb.cd/",
  "https://www.inss.cd/",
  // === Universités RDC ===
  "https://www.unikin.ac.cd/",
  "https://www.upn.ac.cd/",
  "https://www.unilu.ac.cd/",
  "https://www.unikis.ac.cd/",
  "https://www.unibukavu.ac.cd/",
  "https://www.unigom.ac.cd/",
  "https://www.unikol.ac.cd/",
  "https://www.unilu.ac.cd/",
  // === Médias RDC ===
  "https://www.radiookapi.net/",
  "https://www.actualite.cd/",
  "https://www.7sur7.cd/",
  "https://www.politico.cd/",
  "https://www.zoom-eco.net/",
  "https://www.financescongolises.cd/",
  "https://www.groupelesoft.com/",
  "https://www.digitalcongo.net/",
  "https://www.acp.cd/",
  "https://www.radiotvc.net/",
  // === Afrique francophone ===
  "https://www.jeuneafrique.com/pays/republique-democratique-du-congo/",
  "https://www.rfi.fr/fr/tag/rdc/",
  "https://www.france24.com/fr/tag/rdc/",
  "https://www.africanews.com/tag/drc/",
  "https://www.theafricareport.com/tag/drc/",
  "https://www.mongabay.com/country/democratic-republic-of-the-congo/",
  // === Référence mondiale ===
  "https://www.bbc.com/news/world/africa",
  "https://www.reuters.com/world/africa/",
  "https://www.theguardian.com/world/congo",
  "https://www.aljazeera.com/tag/democratic-republic-of-the-congo/",
  "https://www.worldbank.org/en/country/drc",
  "https://www.imf.org/en/Countries/COD",
  "https://www.un.org/en/about-us/member-states/democratic-republic-of-the-congo",
  "https://www.who.int/countries/cod",
  "https://www.unicef.org/drcongo",
  "https://www.unhcr.org/country/drc",
  "https://www.hrw.org/africa/democratic-republic-congo",
  "https://www.amnesty.org/en/location/africa/east-africa-the-horn-and-great-lakes/democratic-republic-of-congo/",
  "https://www.cia.gov/the-world-factbook/countries/congo-democratic-republic-of-the/",
  "https://www.britannica.com/place/Democratic-Republic-of-the-Congo",
  // === Science & tech ===
  "https://www.nature.com/",
  "https://arxiv.org/",
  "https://developer.mozilla.org/",
  "https://www.w3.org/",
  "https://schema.org/",
  // === Écosystème Ayeba (apps sœurs) ===
  "https://jemsa.net/",
  "https://to-tala.com/",
  "https://sombatekaonline.com/",
  "https://omega-web.org/",
  "https://devalpha1.com/",
  "https://ayeba.app/",
  "https://ayeba.app/studio",
  "https://ayeba.app/developers",
  "https://ayeba.app/ayebi",
  // === Shopping RDC ===
  "https://www.jumia.cd/",
  "https://www.yango.com/",
  // === Wikipedia discovery (pages list) ===
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:R%C3%A9publique_d%C3%A9mocratique_du_Congo",
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Ville_en_R%C3%A9publique_d%C3%A9mocratique_du_Congo",
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Personnalit%C3%A9_congolaise",
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Sport_en_R%C3%A9publique_d%C3%A9mocratique_du_Congo",
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Culture_congolaise",
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:%C3%89conomie_de_la_R%C3%A9publique_d%C3%A9mocratique_du_Congo",
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Histoire_de_la_R%C3%A9publique_d%C3%A9mocratique_du_Congo",
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Musique_congolaise",
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Province_de_la_R%C3%A9publique_d%C3%A9mocratique_du_Congo",
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Faune_en_R%C3%A9publique_d%C3%A9mocratique_du_Congo",
  "https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Politique_en_R%C3%A9publique_d%C3%A9mocratique_du_Congo",
  // === Sitemaps majeurs ===
  "https://www.bbc.com/sitemaps/https-sitemap-com-news-1.xml",
  "https://www.reuters.com/sitemap.xml",
  "https://www.radiookapi.net/sitemap.xml",
  "https://www.jeuneafrique.com/sitemap.xml",
  "https://fr.wikipedia.org/sitemap.xml",
];

export const SITEMAP_SEEDS = [
  "https://www.radiookapi.net/sitemap.xml",
  "https://www.actualite.cd/sitemap.xml",
  "https://www.jeuneafrique.com/sitemap.xml",
  "https://www.bbc.com/sitemaps/https-sitemap-com-news-1.xml",
  "https://www.reuters.com/sitemap.xml",
  "https://www.worldbank.org/sitemap.xml",
  "https://www.jumia.cd/sitemap.xml",
];
